# Generated by Django 5.0.7 on 2024-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_site', '0007_alter_menulink_site_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='show_description',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_footer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_header',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_menu',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_pagination',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_search',
            field=models.BooleanField(),
        ),
    ]
